#cloud-config
# Cloud-init configuration for GitHub Actions Runner

users:
  - name: opc
    groups: sudo
    shell: /bin/bash
    homedir: /home/opc
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "${authorized_ssh_key}"

  - name: th3pl4gu3
    groups: sudo
    shell: /bin/bash
    homedir: /home/th3pl4gu3
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "${authorized_ssh_key}"

  - name: githubrunner
    groups: sudo
    shell: /bin/bash
    homedir: /home/githubrunner
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "${authorized_ssh_key}"

packages:
  - curl
  - wget
  - jq
  - libicu
  - openssl-devel
  - git
  - tar

# Setup and configure GitHub runner
runcmd:
  # Create runner directory
  - mkdir -p /home/githubrunner/actions-runner
  - chown -R githubrunner:githubrunner /home/githubrunner/actions-runner

  # Download and extract GitHub Actions runner
  - |
    su - githubrunner -c "
      cd /home/githubrunner/actions-runner
      curl -o actions-runner-linux-arm64-2.327.1.tar.gz -L https://objectstorage.af-johannesburg-1.oraclecloud.com/n/axvq8o9auqqf/b/binaries/o/github%2Factions-runner-linux-arm64-2.327.1.tar.gz
      tar xzf ./actions-runner-linux-arm64-2.327.1.tar.gz
      rm actions-runner-linux-arm64-2.327.1.tar.gz
    "

  # Configure the runner (unattended)
  - |
    su - githubrunner -c "
      cd /home/githubrunner/actions-runner
      ./config.sh \
        --url '${github_org_url}' \
        --token '${github_runner_token}' \
        --name '${runner_name}' \
        --labels '${runner_labels}' \
        --work '${runner_work_dir}' \
        --unattended \
        --replace
    "

  # Install and start the runner as a service
  - |
    cd /home/githubrunner/actions-runner
    ./svc.sh install githubrunner
    ./svc.sh start

  # Create a systemd service override for automatic restart
  - |
    mkdir -p /etc/systemd/system/actions.runner.plagueworks-org.${runner_name}.service.d
    cat > /etc/systemd/system/actions.runner.plagueworks-org.${runner_name}.service.d/override.conf <<EOF
    [Service]
    Restart=always
    RestartSec=10
    StartLimitInterval=0
    EOF

  # Reload systemd and ensure service is enabled
  - systemctl daemon-reload
  - systemctl enable actions.runner.plagueworks-org.${runner_name}.service
  - systemctl restart actions.runner.plagueworks-org.${runner_name}.service

  # Log the installation status
  - echo "GitHub Runner installation completed at $(date)" >> /var/log/github-runner-install.log
  - systemctl status actions.runner.plagueworks-org.${runner_name}.service >> /var/log/github-runner-install.log 2>&1

# Write a simple status check script
write_files:
  - path: /home/githubrunner/check-runner-status.sh
    owner: githubrunner:githubrunner
    permissions: "0755"
    content: |
      #!/bin/bash
      echo "=== GitHub Runner Status ==="
      systemctl status actions.runner.plagueworks-org.${runner_name}.service
      echo ""
      echo "=== Runner Process ==="
      ps aux | grep Runner.Listener | grep -v grep

# Final message
final_message: "GitHub Runner setup completed successfully!"
