#cloud-config
# Cloud-init configuration for GitHub Actions Runner

users:
  - name: opc
    groups: sudo
    shell: /bin/bash
    homedir: /home/opc
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "${authorized_ssh_key}"

  - name: th3pl4gu3
    groups: sudo
    shell: /bin/bash
    homedir: /home/th3pl4gu3
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "${authorized_ssh_key}"

  - name: githubrunner
    groups: sudo
    shell: /bin/bash
    homedir: /home/githubrunner
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "${authorized_ssh_key}"

packages:
  - curl
  - wget
  - jq
  - libicu
  - openssl-devel
  - git
  - tar

# Final message
final_message: "GitHub Runner setup completed successfully!"
