#cloud-config
# Cloud-init configuration for GitHub Actions Runner

users:
  - name: opc
    groups: sudo
    shell: /bin/bash
    homedir: /home/opc
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "${authorized_ssh_key}"

  - name: th3pl4gu3
    groups: sudo
    shell: /bin/bash
    homedir: /home/th3pl4gu3
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "${authorized_ssh_key}"

  - name: githubrunner
    groups: sudo,docker
    shell: /bin/bash
    homedir: /home/githubrunner
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "${authorized_ssh_key}"

package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - jq
  - libicu
  - openssl-devel
  - git
  - tar
  - python3-pip
  - python39-oci-cli

write_files:
  # Set up environment variables
  - path: /etc/environment
    content: |
      GITHUB_PAT=${github_pat}
      GITHUB_ORG=plagueworks-org

      OCI_ZEUS_PROD_CID=${oci_prod_cid_zeus}
      OCI_POSEIDON_PROD_CID=${oci_prod_cid_poseidon}
      OCI_GAIA_PROD_CID=${oci_prod_cid_gaia}
      OCI_HELIOS_PROD_CID=${oci_prod_cid_helios}

    append: true
    permissions: "0644"

  # Run the setup script to configure the GitHub runner
  - path: /tmp/setup_runner.sh
    content: |
      #!/bin/bash
      set -e

      # Configuration
      GITHUB_ORG="plagueworks-org"
      GITHUB_PAT="${github_pat}"

      # Get runner registration token from GitHub API
      RUNNER_TOKEN=$(curl -s -X POST \
          -H "Authorization: token $GITHUB_PAT" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/orgs/$GITHUB_ORG/actions/runners/registration-token" \
          | jq -r '.token')

      # Create runner directory in /opt (better for SELinux)
      mkdir -p /opt/github-runner
      cd /opt/github-runner

      # Download the latest runner package
      curl -o actions-runner-linux-arm64.tar.gz -L https://objectstorage.af-johannesburg-1.oraclecloud.com/n/axvq8o9auqqf/b/binaries/o/github%2Factions-runner-linux-arm64-2.327.1.tar.gz

      # Extract the package
      tar xzf ./actions-runner-linux-arm64.tar.gz

      # Set ownership to githubrunner user
      chown -R githubrunner:githubrunner /opt/github-runner

      # Configure the runner (non-interactive)
      sudo -u githubrunner bash -c "cd /opt/github-runner && ./config.sh --url https://github.com/plagueworks-org --token $RUNNER_TOKEN --unattended --replace"
    permissions: "0755"

  # Create systemd service for the GitHub runner
  - path: /etc/systemd/system/github-runner.service
    content: |
      [Unit]
      Description=GitHub Actions Runner
      After=network.target
      Wants=network.target

      [Service]
      Type=simple
      User=githubrunner
      Group=githubrunner
      WorkingDirectory=/opt/github-runner
      ExecStart=/opt/github-runner/run.sh
      Restart=always
      RestartSec=5
      Environment="GITHUB_PAT=${github_pat}"
      Environment="GITHUB_ORG=plagueworks-org"

      [Install]
      WantedBy=multi-user.target
    permissions: "0644"

  # Setup Python aliases
  - path: /etc/profile.d/python-aliases.sh
    permissions: "0644"
    content: |
      #!/bin/bash
      # System-wide Python aliases
      alias python=python3
      alias pip=pip3
      export PATH=$PATH:/usr/local/bin

  # Setup OCI CLI configuration
  - path: /home/githubrunner/.oci/config
    permissions: "0600"
    content: |
      [OCI-HELIOS]
      user=${oci_user_ocid_helios}
      fingerprint=${oci_fingerprint}
      tenancy=${oci_tenancy_ocid_helios}
      region=af-johannesburg-1
      key_file=/home/githubrunner/.oci/keys/oci_api_key.pem

      [OCI-ZEUS]
      user=${oci_user_ocid_zeus}
      fingerprint=${oci_fingerprint}
      tenancy=${oci_tenancy_ocid_zeus}
      region=af-johannesburg-1
      key_file=/home/githubrunner/.oci/keys/oci_api_key.pem

      [OCI-POSEIDON]
      user=${oci_user_ocid_poseidon}
      fingerprint=${oci_fingerprint}
      tenancy=${oci_tenancy_ocid_poseidon}
      region=uk-south-1
      key_file=/home/githubrunner/.oci/keys/oci_api_key.pem

      [OCI-GAIA]
      user=${oci_user_ocid_gaia}
      fingerprint=${oci_fingerprint}
      tenancy=${oci_tenancy_ocid_gaia}
      region=uk-south-1
      key_file=/home/githubrunner/.oci/keys/oci_api_key.pem

  # Setup OCI Private Keys
  - path: /home/githubrunner/.oci/keys/oci_api_key.pem
    permissions: "0600"
    encoding: b64
    content: ${oci_private_key_base64}

runcmd:
  # Install Docker
  - dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  - dnf install docker-ce -y
  - systemctl start docker
  - systemctl enable docker

  # Add githubrunner user to docker group (if not already done)
  - usermod -aG docker githubrunner
  - usermod -aG docker opc
  - usermod -aG docker th3pl4gu3

  # Ensure githubrunner has full ownership of their home directory
  - chown -R githubrunner:githubrunner /home/githubrunner
  - chmod -R 755 /home/githubrunner

  # Source environment variables and run setup script
  - bash -c "source /etc/environment && /tmp/setup_runner.sh"

  # Enable and start the GitHub runner service
  - systemctl daemon-reload
  - systemctl enable github-runner.service
  - systemctl start github-runner.service

# Final message
final_message: "GitHub Runner setup completed successfully!"
